ik_d8_fetzer_engagement.engagement_entity_type.*:
  type: config_entity
  label: 'Engagement Forms type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
